name: Checkmarx NPM install for Auto PR
on:
  pull_request:
    branches:
      - master
    types:
      - opened

permissions:
  contents: read

jobs:
  npm-install:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Fetch Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - shell: bash
        run: |
          : Update after npm install
          npm install
      
      - shell: bash
        run: |
          : Commit the update
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add --all
          git commit -m "update after npm install"
          git push -u origin HEAD:"${{ github.head_ref }}"
          
        
